# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Daniel Tsui
tagline:             ''
description:         'Software Engineer in SF. \n From Vancouver, Canada. Hacker in Residence at <a href="www.hackreactor.com">Hack Reactor</a>'
url:                 http://sdtsui.com
baseurl:             /
paginate:            4

# About/contact
author:
  name:              Daniel Tsui
  url:               http://sdtsui.com
  email:             danielt213@gmail.com

# Custom vars
version:             1.0.0
