# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Daniel Tsui
tagline:             'Your mind is software. Program it.'
description:         'Software Engineer in SF. From Vancouver, Canada. Hacker in Residence at <a href="//hackreactor.com">Hack Reactor</a> Looking for remote and contract roles in the Bay Area.'
url:                 http://sdtsui.com
baseurl:             /
paginate:            4

# About/contact
author:
  name:              Daniel Tsui
  url:               http://sdtsui.com
  email:             danielt213@gmail.com

# Custom vars
version:             1.0.0
