# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Daniel Tsui
tagline:             'Your mind is software. Program it.<a style="float: right; font-size:28px;" href="https://docs.google.com/document/d/1zVspy3Or6yoy9GzjSk0Hi7yQ2hyzBLf1dJ5wa044B8g"> Resume<a/>'
description:         'Software Engineer in SF. From Vancouver, Canada. Hacker in Residence at <a href="//hackreactor.com">Hack Reactor</a>. Looking for remote and contract roles in the Bay Area. <a href="https://docs.google.com/document/d/1zVspy3Or6yoy9GzjSk0Hi7yQ2hyzBLf1dJ5wa044B8g">Resume</a>.'
url:                 http://sdtsui.com
baseurl:             /
paginate:            4

# About/contact
author:
  name:              Daniel Tsui
  url:               http://sdtsui.com
  email:             danielt213@gmail.com

# Custom vars
version:             1.0.0
